// Visible FAQ and structured data share this source.
export const mcpFaq = [
  { q: 'How does P.R.O. connect Apple Health to an AI assistant?', a: 'P.R.O. syncs the Apple Health categories you allow and exposes them through its MCP connector at https://mcp.proapp.uk. Add the connector in your assistant and approve access with a one-time code from P.R.O. The assistant can then answer questions using your synced workouts, sleep and metrics.' },
  { q: 'Which AI assistants have been tested?', a: 'ChatGPT, Claude, Codex and Grok. Interactive P.R.O. cards are confirmed in ChatGPT and Claude. Other clients need remote MCP over Streamable HTTP and OAuth support. Perplexity setup is still being verified.' },
  { q: 'Can I set up the connection in the ChatGPT iPhone app?', a: 'Add the custom connector on chatgpt.com first; it then works in the iPhone app too. The recorded iPhone interface does not offer custom MCP server setup.' },
  { q: 'Is the P.R.O. connector free?', a: 'The connector is included in P.R.O., which is free to download. Your assistant’s plan and workspace permissions must allow custom MCP connections. ChatGPT and Codex were tested with Pro; other plans have not been verified.' },
  { q: 'Does connecting Codex also connect regular ChatGPT chats?', a: 'No. In the recorded Mac app, MCP servers added in Settings → Plugins → MCPs belong to Codex in Work. Regular ChatGPT chats need the separate setup on chatgpt.com.' },
  { q: 'What if my connection code expires?', a: 'Get a new six-character code in P.R.O.; it works once and lasts 10 minutes. On iPhone, Open P.R.O. on the authorization page generates and copies it for you. Return, tap Paste, then Connect. On a computer, get the code on your iPhone and type it into the page.' },
  { q: 'What data can the assistant access?', a: 'Only the categories you allow: profile, goals, daily metrics, workouts, workout routes, sleep, heart rate and HRV, and coach memory. Review the switches in the connection confirmation and change access later in P.R.O.' },
  { q: 'Can an assistant change my data?', a: 'Saving coach notes is optional and off by default. The connector also supports a request for a fresh sync. It does not provide tools for deleting your data, making payments or sending messages.' },
  { q: 'Why is my latest workout missing?', a: 'The assistant reads data synced from your iPhone to P.R.O. Open P.R.O. to sync the latest workouts and metrics, and check Apple Health and assistant access permissions. Detailed routes and other data may require an on-demand request from the assistant.' },
  { q: 'How do I disconnect an assistant?', a: 'Open Settings → MCP Connect in P.R.O. Under Connected, tap × beside the assistant, then confirm Disconnect. Removing the connector only inside the assistant does not revoke its P.R.O. access.' },
];
